---
machines:
  hosts:
    VM-u20:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"

routers:
  hosts:

    ciscoA:
      ansible_host: 192.168.12.241
      # group-specific configuration
      interfaceHigh_conf:
        address: 172.16.--X+1--.110 255.255.255.0
        ospf_network_type: broadcast
      interfaceLow_conf:
        address: 10.0.--X+201--.1 255.255.255.252
        ospf_network_type: point-to-point
      ospf_conf:
        router_id: --G--.--G--.--G--.4
        networks:
        - address: --G--.--G--.--G--.4 255.255.255.255
          area: 0
        - address: 10.0.--X+201--.0 255.255.255.252
          area: 0
        - address: 172.16.--X+1--.0 255.255.255.0
          area: 0

    ciscoB:
      ansible_host: 192.168.12.242
      # group-specific configuration
      interfaceHigh_conf:
        address: 10.0.--X+201--.2 255.255.255.252
        ospf_network_type: point-to-point
      interfaceLow_conf:
        address: 10.0.--X+202--.2 255.255.255.252
        ospf_network_type: point-to-point
      ospf_conf:
        router_id: --G--.--G--.--G--.5
        networks:
        - address: --G--.--G--.--G--.5 255.255.255.255
          area: 0
        - address: 10.0.--X+201--.0 255.255.255.252
          area: 0
        - address: 10.0.--X+202--.0 255.255.255.252
          area: 0

    ciscoC:
      ansible_host: 192.168.12.243
      # group-specific configuration
      interfaceHigh_conf:
        address: 10.0.--X+202--.1 255.255.255.252
        ospf_network_type: point-to-point
      interfaceLow_conf:
        address: 172.16.--X+2--.120 255.255.255.0
        ospf_network_type: broadcast
      ospf_conf:
        router_id: --G--.--G--.--G--.6
        networks:
        - address: --G--.--G--.--G--.6 255.255.255.255
          area: 0
        - address: 10.0.--X+202--.0 255.255.255.252
          area: 0
        - address: 172.16.--X+2--.0 255.255.255.0
          area: 0

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: netlab
    ansible_password: routerlab
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: routerlab
    # group-specific configuration
    interfaceLow_name: Vlan--G--
    interfaceHigh_name: Vlan--G+4--
    ospf_cost: 1
    ospf_loopback: Loopback--G--
    ospf_process_id: --X--
