---
- name: Cisco routers configuration for LA1
  hosts: routers
  gather_facts: false

  tasks:

  - name: Configure interfaces
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "{{ interfaceLow_name }}"
        ipv4:
        - address: "{{ interfaceLow_conf.address }}"
      - name: "{{ interfaceHigh_name }}"
        ipv4:
        - address: "{{ interfaceHigh_conf.address }}"
      state: merged
    
  - name: Reset OSPF configuration of interfaces
    cisco.ios.ios_ospf_interfaces:
      config:
        - name: "{{ interfaceLow_name }}"
        - name: "{{ interfaceHigh_name }}"
      state: deleted

  - name: Show IP configuration of interfaces
    cisco.ios.ios_command:
      commands: show ip interf brief
    register: task_output

  - debug: 
      var: task_output.stdout_lines

