---
- name: Cisco routers configuration for LA1
  hosts: routers
  gather_facts: false

  tasks:

  - name: Configure interface FE Low (G)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceLow_name }}"
      lines:
      - "ip address {{ interfaceLow_conf.address }}"
      - "no ip ospf cost"
      - "no ip ospf network"

  - name: Configure interface FE High (G+4)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceHigh_name }}"
      lines:
      - "ip address {{ interfaceHigh_conf.address }}"
      - "no ip ospf cost"
      - "no ip ospf network"

  - name: Show IP configuration of interfaces
    cisco.ios.ios_command:
      commands: show ip interf brief
    register: task_output

  - debug: 
      var: task_output.stdout_lines

