---
- name: Cisco routers configuration for LA1 - topology
  hosts: routers
  gather_facts: false

  tasks:

  - name: Reset interface FE Low (G)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceLow_name }}"
      lines:
      - "no ip address"
      - "no ip ospf cost"
      - "no ip ospf network"

  - name: Reset interface FE High (G+4)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceHigh_name }}"
      lines:
      - "no ip address"
      - "no ip ospf cost"
      - "no ip ospf network"

  - name: Configure interface FE Low (G)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceLow_name }}"
      lines:
      - "ip address {{ interfaceLow_conf.address }}"
      - "no ip ospf cost"
      - "no ip ospf network"

  - name: Configure interface FE High (G+4)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceHigh_name }}"
      lines:
      - "ip address {{ interfaceHigh_conf.address }}"
      - "no ip ospf cost"
      - "no ip ospf network"

  - name: Show running configuration and IP configuration of interfaces
    cisco.ios.ios_command:
      commands:
      - "show running-config"
      - "show ip interface brief"
    register: task_output

  - debug: 
      var: task_output.stdout_lines

