---
machines:
  hosts:
  
    VM-u20:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"

routers:
  hosts:

    ciscoA:
      ansible_host: 192.168.12.241
      # group-specific configuration
      interfaceHigh_conf:
        address: 172.16.--X+1--.110 255.255.255.0
      interfaceLow_conf:
        address: 10.0.--X+201--.1 255.255.255.252

    ciscoB:
      ansible_host: 192.168.12.242
      # group-specific configuration
      interfaceHigh_conf:
        address: 10.0.--X+201--.2 255.255.255.252
      interfaceLow_conf:
        address: 10.0.--X+202--.2 255.255.255.252

    ciscoC:
      ansible_host: 192.168.12.243
      # group-specific configuration
      interfaceHigh_conf:
        address: 10.0.--X+202--.1 255.255.255.252
      interfaceLow_conf:
        address: 172.16.--X+2--.120 255.255.255.0

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: netlab
    ansible_become: yes
    ansible_become_method: enable
    # group-specific configuration
    interfaceLow_name: Vlan--G--
    interfaceHigh_name: Vlan--G+4--
