---
- name: Cisco routers configuration for LA3 - BGP
  hosts: routers
  gather_facts: false

  tasks:

  - name: Reset interface FE Low (G)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceLow_name }}"
      lines:
      - "no ip address"
      - "no ip ospf cost"
      - "no ip ospf network"
    when: interfaceLow_name is defined

  - name: Reset interface FE High (G+4)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceHigh_name }}"
      lines:
      - "no ip address"
      - "no ip ospf cost"
      - "no ip ospf network"
    when: interfaceHigh_name is defined

  - name: Configure interface FE Low (G)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceLow_name }}"
      lines:
      - "ip address {{ interfaceLow_conf.address }}"
    when: interfaceLow_name is defined

  - name: Configure interface FE High (G+4)
    cisco.ios.ios_config:
      parents: "interface {{ interfaceHigh_name }}"
      lines:
      - "ip address {{ interfaceHigh_conf.address }}"
    when: interfaceHigh_name is defined

  - name: Configure BGP peering
    cisco.ios.ios_config:
      parents: "router bgp {{ bgp_conf.asn }}"
      lines:
      - "neighbor {{ item.address }} remote-as {{ item.asn }}"
    loop: "{{ bgp_conf.neighbors }}"

  - name: Configure BGP directly connected networks
    cisco.ios.ios_config:
      parents: "router bgp {{ bgp_conf.asn }}"
      lines:
      - "network {{ item.prefix }} mask {{ item.mask }}"
    loop: "{{ bgp_conf.networks }}"

  - name: Show running configuration
    cisco.ios.ios_command:
      commands: show running-config
    register: task_output

  - debug: 
      var: task_output.stdout_lines

