---
machines:
  hosts:
    VM-u20:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/env python3"

routers:
  hosts:

    ciscoA:
      ansible_host: 192.168.12.241
      # group-specific configuration
      interfaceHigh_name: Vlan--G+4--
      interfaceHigh_conf:
        address: 172.16.--X+1--.110 255.255.255.0
      bgp_conf:
        asn: 400
        neighbors:
        - address: 172.16.--X+1--.10
          asn: --X+100--
        networks:
        - prefix: 172.16.--X+1--.0
          mask: 255.255.255.0

    ciscoC:
      ansible_host: 192.168.12.243
      # group-specific configuration
      interfaceLow_name: Vlan--G--
      interfaceLow_conf:
        address: 172.16.--X+2--.120 255.255.255.0
      bgp_conf:
        asn: 600
        neighbors:
        - address: 172.16.--X+2--.20
          asn: --X+200--
        networks:
        - prefix: 172.16.--X+2--.0
          mask: 255.255.255.0

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: netlab
    ansible_become: yes
    ansible_become_method: enable
    bgp_loopback: Loopback0    
